[package]
name = "tycho-simulation-ts"
version = "0.1.0"
edition = "2021"
description = "TypeScript bindings for Tycho simulation"
license = "MIT"
repository = "https://github.com/dewiz-xyz/tycho-simulation-ts"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]
name = "tycho_simulation_ts"

[dependencies]
napi = { version = "2.15.0", default-features = false, features = ["napi6"] }
napi-derive = "2.15.0"
tycho-simulation = { git = "https://github.com/propeller-heads/tycho-simulation", tag = "0.70.0" }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
num-traits = "0.2"
num-bigint = "0.4"

[build-dependencies]
napi-build = "2.1.0"
