/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AmountOutResult {
  pool: string
  amountsOut: Array<number>
  gasUsed: Array<number>
}
export declare class SimulationClient {
  constructor(tychoUrl: string, apiKey?: string | undefined | null, tvlThreshold?: number | undefined | null)
  getSpotPrice(token0Address: string, token1Address: string): number
  getAmountOut(tokenInAddress: string, tokenOutAddress: string, amountsIn: Array<number>): Array<AmountOutResult>
}
